import { build } from "esbuild";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const distDir = path.join(root, "dist");

// Ensure dist exists. Non-destructive: esbuild overwrites dist/browser.js and we
// regenerate dist/source.js; the main `build` script chains `tsc` afterwards which
// overwrites its own emitted files. Avoid rmSync so pretest (this script) does not
// wipe the tsc-emitted dist/index.js that other packages resolve at test time.
mkdirSync(distDir, { recursive: true });

// 1. Bundle the browser runtime into a single self-executing IIFE. The entry has no
//    exports — it attaches `window.spherse` as a side effect, guarded by
//    `window.__SPHERSE_SDK__` so loading it twice is a no-op.
await build({
  entryPoints: [path.join(root, "src/runtime/index.ts")],
  bundle: true,
  format: "iife",
  target: ["es2019"],
  outfile: path.join(distDir, "browser.js"),
  minify: false,
  legalComments: "none",
  logLevel: "info",
});

// 2. Expose the bundle text as a string constant (SDK_SOURCE) so the renderer can inline
//    it into srcDoc <script> tags and the server can serve identical bytes, without either
//    consumer needing to bundle the runtime itself. tsc (run next via the build script)
//    emits the rest of dist/.
const bundle = readFileSync(path.join(distDir, "browser.js"), "utf8");
const escaped = bundle
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

writeFileSync(
  path.join(distDir, "source.js"),
  `// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.\n// Bundled browser runtime (dist/browser.js) as a string, for inline <script> injection.\nexport const SDK_SOURCE = \`${escaped}\`;\n`,
);
writeFileSync(
  path.join(distDir, "source.d.ts"),
  `// AUTO-GENERATED by scripts/build.mjs.\n/** Full text of the browser SDK bundle (dist/browser.js). */\nexport declare const SDK_SOURCE: string;\n`,
);

console.log("[sdk] bundled browser.js (%d bytes) and generated source.js", bundle.length);
