import esbuild from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import path from "node:path";

const root = process.cwd();
const browserOut = path.join(root, "dist", "browser.js");

function regenerate() {
  const bundle = readFileSync(browserOut, "utf8");
  const escaped = bundle
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  writeFileSync(
    path.join(root, "dist", "source.js"),
    `// AUTO-GENERATED by scripts/build.mjs — do not edit by hand.\n// Bundled browser runtime (dist/browser.js) as a string, for inline <script> injection.\nexport const SDK_SOURCE = \`${escaped}\`;\n`,
  );
  console.log("[sdk] regenerated source.js");
}

const ctx = await esbuild.context({
  entryPoints: [path.join(root, "src/runtime/index.ts")],
  bundle: true,
  format: "iife",
  target: ["es2019"],
  outfile: browserOut,
  minify: false,
  legalComments: "none",
  plugins: [
    {
      name: "regenerate-source",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) regenerate();
        });
      },
    },
  ],
});

await ctx.watch();

const tsc = spawn("tsc", ["--watch", "--preserveWatchOutput"], { stdio: "inherit" });
tsc.on("close", (code) => process.exit(code ?? 0));

function shutdown() {
  tsc.kill();
  await ctx.dispose();
  process.exit(0);
}
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

console.log("[sdk] watching src/runtime → dist/browser.js + dist/source.js | tsc --watch");
